services:
  astro:
    restart: unless-stopped
    image: dockerregistry.hlab.es/postifyai-landing:latest
    ports:
      - '4321:4321'
    env_file:
      - .env

  watchtower:
    restart: unless-stopped
    image: containrrr/watchtower
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /home/${USER}/.docker/config.json:/config.json
    # Make watchtower check for updates every 12 hours
    command: --interval 43200
